OOP school library: add basic UI
SAZZAD1Q2/School-Library pull request #6
Opened 2023-09-01 16:50 UTC by SAZZAD1Q2

Create a app.rb file that will serve as a console app entry point
In main.rb I define the entry point, this will be a method called main that is invoked at the end of the file

2023-09-01 18:45 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @SAZZAD1Q2 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Build interactive console apps.
- ✔️ Run a program using the command line.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 18:45 UTC, abdulhamiid commented on main.rb
> +    puts "\n"
When I started your app, I could not access all the available options of the app 👇 

![image](https://github.com/SAZZAD1Q2/School-Library/assets/78251927/36438fe9-5d32-4281-a244-1ea885238dc8)

According to the [project requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_ui.md), our console app should behave in the same way as it is in the [example video](https://www.youtube.com/watch?v=vkkgrhD6aXQ) 😊🛠.

![image](https://github.com/SAZZAD1Q2/School-Library/assets/78251927/4ce9c8b9-0f00-445a-890f-cda5f80fa0fd)

Example video
![image](https://github.com/SAZZAD1Q2/School-Library/assets/78251927/dd76d907-b90f-4992-bc20-afee3ef31529)

2023-09-01 18:45 UTC, abdulhamiid commented on app.rb
> +  end
I encountered `ArgumentError` while creating a person.

![tempsnip](https://github.com/SAZZAD1Q2/School-Library/assets/78251927/e800b965-ae46-4cc8-8264-714426d50348)

Please fix this issue so that the console app works as expected.

2023-09-02 05:25 UTC, shella12 approved these changes
Hi @SAZZAD1Q2, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Console app works as expected ✔️ 
- Fixed error form `Create Person` option 👍 
- Implemented all requirements 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-02 05:38 UTC, merged